os: linux
language: python

git:
  depth: 3

env:
  global: TERM=dumb

matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.2"
    - python: "3.6"
    - python: "nightly"
    - python: "pypy"
    - python: "pypy-5.3.1"
    - python: "pypy3-2.4.0"

    - env: Python=2.7
      os: osx
      language: generic
      before_install:
        - export TRAVIS_PYTHON_VERSION="$Python"
        - brew update
        - brew install p7zip
  allow_failures:
    - os: osx
  fast_finish: true

addons:
  apt:
    packages:
      - p7zip-full

script: python main.py
